version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
      - ./rabbitmq/etc/:/etc/rabbitmq/
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
      - 15675:15675

volumes:
  rabbitmq-data:
  rabbitmq-logs: